#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("udp_server", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/udp_server.rb", config.to_hash